[package]
name = "minisafe-gui"
version = "0.0.1"
readme = "README.md"
description = "Minisafe GUI"
repository = "https://github.com/revault/minisafe"
license = "BSD-3-Clause"
authors = ["Edouard Paris <m@edouard.paris>", "Daniela Brozzoni <danielabrozzoni@protonmail.com>"]
edition = "2018"
resolver = "2"

[[bin]]
name = "minisafe-gui"
path = "src/main.rs"

[dependencies]
async-hwi = { git = "https://github.com/revault/async-hwi", branch = "master" }
minisafe = { git = "https://github.com/edouardparis/minisafe", branch ="gethistory", default-features = false}
backtrace = "0.3"
base64 = "0.13"

iced = { version = "0.4", default-features= false, features = ["tokio", "wgpu", "svg", "qr_code", "pure"] }
iced_native = "0.5"
iced_lazy = { version = "0.1.1", features = ["pure"] }
iced_pure = "0.2.2"

tokio = {version = "1.21.0", features = ["signal"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging stuff
log = "0.4"
fern = "0.6"

dirs = "3.0.1"
toml = "0.5"

chrono = "0.4"

[target.'cfg(windows)'.dependencies]
uds_windows = "0.1.5"

[dev-dependencies]
tokio = {version = "1.9.0", features = ["rt", "macros"]}
